[package]
name = "simple-shell"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "single"
path = "src/single.rs"

[[bin]]
name = "multi"
path = "src/multi.rs"

[[bin]]
name = "readable"
path = "src/readable.rs"