[package]
name = "server"
version = "0.1.0"
edition = "2021"
description = "UDP Server"

[dev-dependencies]
common-lib = {version="0.1.0",path="../common-lib"}

[dependencies]
tokio = {version="1.28.2", features=["full"]}