[package]
name = "calc"
version = "0.1.0"
edition = "2021"
description = "A tiny dummy calculator which written in rust and wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
