[package]
name = "bad-or-good"
version = "0.1.0"
edition = "2021"
description = "Step by step into Green Coding Principles"
authors = ["Burak Selim Şenyurt"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "green_coding_benchmark"
harness = false