[package]
name = "bookshop-grpc-service"
description = "Basit bir gRPC servis kullanımı örneği"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.8"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.4"
