[package]
name = "curlc"
version = "0.1.0"
edition = "2021"
description = "Bir dosyadan http talepleri okuyan öğretiye ait çalışma"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking"] }
