[package]
name = "writing-web-server"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members=[
    "a-simple-web-server",
    "multi-thread-web-server",
    "a-non-blocking-server"
]
