[package]
name = "publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.14", features = ["json"] } # HTTP Request için
serde = { version = "1.0.154", features = ["derive"] } # Serileştirme işlemleri için
serde_json = "1.0.94" # serde'nin JSON serileştirme desteği için
tokio = { version = "1.26.0", features = ["full"] } # async desteği için
urlencoding = "2.1.2" # url-encode parametresi kullanımı için
kafka = "0.9.0" # Kafka broker'ı ile konuşmak için
