[package]
name = "space_age"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diff = "0.1.13"
ignore = { version = "0.4.21", features = [] }
