[package]
name = "the_grid"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
rand="0.8.5"
getrandom = { version = "0.2.6", features = ["js"] }

[lib]
crate-type = ["cdylib"]