[package]
name = "get-lorem-picsum"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.27.0", features = ["full"] }
