[package]
name = "use-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
#colored = "2.0.0"
diesel = { version = "2.0.4", features = ["sqlite"] }
dotenvy = "0.15.7"
serde = { version = "1.0.160", features = ["derive"] }