[package]
name = "almanac_data"
version = "0.1.0"
edition = "2021"

[dependencies]
# Aşağıdaki bağımlılıklar workspace'teki cargo.toml'dan alınıyor
sea-orm = {workspace = true}
tracing = {workspace = true}
testcontainers = {workspace = true}
tokio = {workspace = true}