pub const HTTP_OK: &str = "HTTP/1.1 200 OK";
pub const HTTP_NOT_FOUND: &str = "HTTP/1.1 404 NOT FOUND";
pub const CONTENT_TYPE: &str = "Content-Type: application/json";
pub const POST_ISSUE: &str = "POST /issues HTTP/1.1";
pub const GET_HELLO: &str = "GET /hello HTTP/1.1";
pub const GET_ALL_ISSUES: &str = "GET /issues HTTP/1.1";
pub const GET_ISSUE: &str = "GET /issues/";
pub const DELETE_ISSUE: &str = "DELETE /issues/";
pub const POST_SKIP_COUNT: usize = 10;
