version: '3.3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_HOST: 127.0.0.1
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080