[package]
name = "ggdb_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
nom_locate = "4.1.0"
serde = {workspace = true}
thiserror = {workspace = true}
miette = {workspace = true}
