[package]
name = "hashdis"
version = "0.1.0"
edition = "2021"
description = "Redis clone"

[dependencies]
async-trait = "0.1.68"
bytes = "1.4.0"
clap = { version = "4.2.4", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
tokio = { version = "1.28.0", features = ["full"] }
