[package]
name = "client"
version = "0.1.0"
edition = "2021"
description = "UDP Client App"

[dependencies]
tokio = {version="1.28.2", features=["full"]}
serde = {version="1.0.163",features=["derive"]}
bincode="1.3.3"
common-lib = {version="0.1.0",path="../common-lib"}
